config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings
  
  root to: 'pages#home'
  get '/listings', to: 'listings#index'
  get '/listings/:id', to: 'listings#show'
  get '/listings/new', to: 'listings#new'
  post '/listings', to: 'listings#create'
  get '/listings/:id/edit', to: 'listings#edit'
  put '/listings/:id', to: 'listings#update'
  delete 'listings/:id', to:'listings#destroy'
  get '/search', to: 'listings#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord

  # these are validations to make sure that these are all entered prior to creating a listing
  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
  
  # each listing MUST have a user that is creating it
  belongs_to :user

  # a listing will have a picture in it too
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # this allows a user to create multiple listings 
  has_many :listings

  # devise authentications for users
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # ensure that if the user is logged in, only then they can create, edit, update or delete a listing. 
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # if the user is the owner of the listing, only then can they edit or delete the listing.
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    @listings = Listing.all
  end

  # individual listing page
  def show
  end

  # method for creating a new listing
  def new
    @listing = Listing.new
  end

  # method for editing a listing
  def edit
  end

  # search logic. if the search is empty, then redirect to homepage.
  # if the search has something entered, it will transform what was entered and make it lowercase. 
  # the search will take all listing titles and transform them into lowercase too, and try to match what the user entered with any titles.
  def search
    if params[:search].blank?
      redirect_to root_path and return
    else
      @parameter = params[:search].downcase
      @listingMatch = Listing.where("lower(title) LIKE ?", "%#{@parameter}%")
    end
  end

  # this is the logic for creating a new listing. it must take the respected parameters, otherewise it will not be made.
  def create
    @listing = Listing.new(title: listing_params[:title], price: listing_params[:price], description: listing_params[:description], user_id: current_user.id, picture: listing_params[:picture])
    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        redirect_to listings_url, notice: "#{@listing.title} was not made"
      end
    end
  end

  # edit listing logic. if a user is the creator or admin, then they can update the listing. otherwise, they will be redirected to the homepage.
  def update
    if current_user==@listing.user or current_user.admin?
      respond_to do |format|
        # must take the parameters specified in listing_params
        if @listing.update(listing_params)
          format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
          format.json { render :show, status: :ok, location: @listing }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to index
    end
  end

  # method for deleting a listing
  def destroy
    @listing.destroy

    redirect_to listings_url, notice: "#{@listing.title} was deleted."
  end

  private
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # the parameters that MUST be given to make or update a listing
    def listing_params
      params.require(:listing).permit(:title, :price, :description, :user_id, :picture)
    end

    # the logic to check to make sure a user is either an administrator or the creator of a listing
    def check_owner
      if !current_user.admin? or !current_user.id==@listing.user_id
        redirect_to listings_url, alert: "You are not the owner of this listing!"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Show the most recent listings on the homepage, newest to oldest, but only limit to 3 listings 
  def home
    @listings = Listing.order("created_at desc").limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bussin Books</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/listings/_form.html.erb
<%# 
  This is how the errors are via the form, which is used for the edit page of a listing 
%>

<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>


      <%# 
        This prints each error message that may have occured while editing a listing
      %>
      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Bootstrap styled form  -->
  <div class="card">
    <div class="card-body">

      <!-- this class is a shortcut for applying a bottom margin of 3px -->
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, { class: "form-control", required: true } %>
      </div>

      <div class="mb-3">
        <%= form.label :price, class: "form-label" %>
        <%= form.text_field :price, { class: "form-control", required: true } %>
      </div>

      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_field :description, { class: "form-control", required: true } %>
      </div>

      <div class="mb-3">
        <%= form.label :picture, class: "form-label" %>
        <%= form.file_field :picture, { class: "form-control-file", accept: "image/jpg, image/png, image/jpeg", required: true } %>
      </div>

      <div class="actions">
        <%= form.submit "Update" %>
      </div>

    </div>
  </div>
<% end %>

app/views/listings/edit.html.erb
<!-- Navbar -->
<%= render "shared/navbar" %>

<h1>Edit Listing</h1>

<!-- This displays the _form.html.erb file in the /id/edit url -->
<%= render 'form', listing: @listing %>

<br>

<!-- Links to show the listing or go back to all of the listings  -->
<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

<!-- Footer -->
<%= render "shared/footer" %> 

app/views/listings/index.html.erb
<!-- Navbar -->
<%= render "shared/navbar" %>

<header class="heading">
  <h1>Browse Listings</h1>
<header>

<!-- 
  The following is how each listing will be displayed in the /listings page. 
  Using bootstrap to style, each item will be inserted into a position in the row.
-->

<div class="row">
<% @listings.each do |listing| %>
  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">

    <!-- 
      This checks to see if the listing has an image, and if it does, displays it with some bootstrap styling.
      This is done because during testing, there were listings without images. This will be updated later
     -->
      <% if listing.picture.attached? %>
        <%= image_tag listing.picture, alt: "image", class: "card-img-top" %>
      <% end %>

      <div class="card-body">
        <h4 class="card-title"><%= link_to listing.title, listing %></h4>
        <p class="card-text">$<%= listing.price %></p>
        <p class="card-text"><%= listing.description %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Show', listing %></button>
          </div>
          <small class="text-muted"><%= listing.created_at %> by <%= listing.user.username %></small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<br>

<!-- A link to create a new listing -->
<%= link_to 'New Listing', new_listing_path %>

<!-- Footer -->
<%= render "shared/footer" %> 

app/views/listings/new.html.erb
<!-- Navbar -->
<%= render "shared/navbar" %>

<h1>New Listing</h1>


<!--
  This form is for creating a listing. It shows displays each error if there are any.
-->
<%= form_with(model: @listing) do |form| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <!-- 
    The form itself, with styling utilising bootstrap.
  -->
  <div class="card">
    <div class="card-body">

      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, { class: "form-control", required: true } %>
      </div>

      <div class="mb-3">
        <%= form.label :price, class: "form-label" %>
        <%= form.text_field :price, { class: "form-control", required: true } %>
      </div>

      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_field :description, { class: "form-control", required: true } %>
      </div>

      <div class="mb-3">
        <%= form.label :picture, class: "form-label" %>
        <%= form.file_field :picture, { class: "form-control-file", accept: "image/jpg, image/png, image/jpeg", required: true } %>
      </div>

      <div class="actions">
        <%= form.submit "Create" %>
      </div>
<% end %>
</div>
<br>
<%= link_to 'Back', listings_path %>
</div>


<!-- Footer -->
<%= render "shared/footer" %> 

app/views/listings/search.html.erb
<!-- 
  This page is essentially the same as /listings, but this is specifically for search results when a user searches for a listing.
-->

<!-- Navbar -->
<%= render "shared/navbar" %>

<header class="heading">
  <h1>Browse Results</h1>
<header>

<div class="row">
<% @listingMatch.each do |listing| %>
  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
      <% if listing.picture.attached? %>
        <%= image_tag listing.picture, alt: "image", class: "card-img-top" %>
      <% end %>

      <div class="card-body">
        <h4 class="card-title"><%= link_to listing.title, listing_url(listing.id) %></h4>
        <p class="card-text">$<%= listing.price %></p>
        <p class="card-text"><%= listing.description %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Show', listing %></button>
          </div>
          <small class="text-muted"><%= listing.created_at %> by <%= listing.user.username %></small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<br><br>
<%= link_to 'Return Home', root_path %>

<!-- Footer -->
<%= render "shared/footer" %> 

app/views/listings/show.html.erb
<!-- Navbar -->
<%= render "shared/navbar" %>

<p id="notice"><%= notice %></p>

  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
      <% if @listing.picture.attached? %>
        <%= image_tag @listing.picture, alt: "Book Image", class: "card-img-top" %>
      <% end %>

      <div class="card-body">
        <h4 class="card-title"><%= @listing.title %></h4>
        <p class="card-text">$<%= @listing.price %></p>
        <p class="card-text"><%= @listing.description %></p>
        <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted"><%= @listing.created_at %> by <%= @listing.user.username %></small>
        </div>
      </div>
    </div>
  </div>

<!-- 
  The following code checks to see if the current user looking at a single listing is either logged in, an administrator, or the same user as the one who created the listing.
  If the user is signed in and an administrator, OR they are the creator of the listing, then these edit and delete buttons will be visible to them. Otherwise, they are not shown.
-->

<% if user_signed_in? and (current_user.admin? or current_user.id==@listing.user_id) %>
  <%= link_to 'Destroy', @listing, method: :delete, data: {confirm: "Are you sure you want to delete this?"} %>
  <%= link_to 'Edit', edit_listing_path(@listing) %>
<% end %>

<%= link_to 'Back', listings_path %>


<!-- Footer -->
<%= render "shared/footer" %> 

app/views/pages/home.html.erb
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bussin' Books</title>
</head>
<body>
    <!-- Navbar -->
        <%= render "shared/navbar" %>

    <!-- Main Body Content -->
        <main>
            <!-- Bootstrap Layout for showing items on homepage -->
              <div class="album py-5">
                <div class="container">
                <p>Here are some most recent listings!</p>

              <!-- Recent Listings for homepage -->
                <div class="row">
                  <%= render "shared/recent" %>
                </div>

    <!-- Footer -->
          <%= render "shared/footer" %> 
        </main>
    </div>
</body>

app/views/shared/_footer.html.erb
<!-- Footer with bootstrap styling -->
<footer class="text-muted">
  <div class="container">
    <p>Bussin' Books &copy; 2022.</p>
  </div>
</footer> 

app/views/shared/_navbar.html.erb
<!-- Navbar that collapses into a more accessible navigation menu when screens are too small  -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Bussin' Books</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#toggleContent" aria-controls="toggleContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="toggleContent">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
              <%=link_to "Buy", "/listings", class: "nav-link"%>
          </li>
          <li class="nav-item">
              <%=link_to "Sell", new_listing_path, class: "nav-link"%>
          </li>
      </ul>

      <!-- 
      This checks to see if the user is signed in, if they are, the navbar will only show a Log Out link
      If they aren't signed in, then the navbar will display a Register and Login button.
       -->

      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <%if user_signed_in?%>
            <li class="nav-item">
              <%=link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
            </li>
          
          <%else%>
            <li class="nav-item">
              <%=link_to "Register", new_user_registration_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Login", new_user_session_path, class: "nav-link"%>
            </li>
          <%end%>
      
      <!--
      The defines the search field in the navbar, using bootstrap for positioning and styling.
      -->

          <%= form_tag(search_path, :method => "get") do %>
          <div class="form-inline my-2 my-lg-0">
            <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
            <div class="input-group-btn">
          <% end %>
      </ul>
  </div>
</nav>

app/views/shared/_recent.html.erb
<p id="notice"><%= notice %></p>
<!-- The logic to show each new listing on the homepage -->
<% @listings.each do |listing| %>
  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
      <% if listing.picture.attached? %>
        <%= image_tag listing.picture, alt: "memes", class: "card-img-top" %>
      <% end %>

      <div class="card-body">
        <h4 class="card-title"><%= link_to listing.title, listing %></h4>
        <p class="card-text">$<%= listing.price %></p>
        <p class="card-text"><%= listing.description %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'Show', listing %></button>
          </div>
          <small class="text-muted"><%= listing.created_at %> by <%= listing.user.username %></small>
        </div>
      </div>
    </div>
  </div>
<% end %>